apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: portfolio
data:
  APP_ENV: "local"
  APP_DEBUG: "true"
  APP_URL: "https://frontend.portfolio.kube"
  SSO_URL: "https://sso.portfolio.kube"
  SSO_REDIRECT_URI: "https://frontend.portfolio.kube/oauth/callback"
