apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/szymonborowski/portfolio-frontend
    newName: portfolio-frontend
    newTag: v0.0.5

patches:
  - path: configmap-patch.yaml
  - path: ingress-patch.yaml
  - path: deployment-patch.yaml
